steps:
- id: 'Deploy to Environment'
  name: 'gcr.io/cloud-builders/sp201812123'
  args: [
    'gcloud'
    'app', 
    'deploy', 
    'app.yaml',
    '--version=20181912',
    '--no-promote',
    '--quiet'
  ]